from filinglens.llm.base import BaseLLMProvider
from filinglens.llm.response import LLMResponse
from filinglens.rag.context import ContextAssembler
from filinglens.rag.prompts import RagPromptBuilder
from filinglens.utils.timer import Timer
from filinglens.utils.logging import get_logger

logger = get_logger(__name__)


class QAService:
    """Orchestrates RAG retrieval, context assembly, and LLM text generation."""

    def __init__(
        self,
        retriever,
        llm: BaseLLMProvider,
    ):
        self.retriever = retriever
        self.llm = llm
        self.context_assembler = ContextAssembler()
        self.prompt_builder = RagPromptBuilder()

    def answer(
        self,
        question: str,
        company: str | None = None,
        year: str | None = None,
        top_k: int = 5,
    ) -> tuple[LLMResponse, list]:
        
        filters = {}
        if company:
            filters["company"] = company
        if year:
            filters["year"] = year

        with Timer() as ret_timer:
            results = self.retriever.search(
                question, 
                top_k=top_k, 
                filters=filters if filters else None,
            )
            
        logger.info(
            "Retrieved %d chunks in %.2f ms", 
            len(results), 
            ret_timer.elapsed_ms,
        )

        context_blocks = self.context_assembler.assemble(results)
        
        prompt = self.prompt_builder.build(question, context_blocks)
        
        logger.info("Prompt assembled: length %d chars", len(prompt.system) + len(prompt.user))

        with Timer() as llm_timer:
            llm_response = self.llm.generate(
                system=prompt.system, 
                user=prompt.user,
            )
            
        logger.info(
            "LLM output %r generated by %s in %.2f sec", 
            llm_response.answer[:30] + "...",
            llm_response.model,
            llm_timer.elapsed_ms / 1000.0,
        )
        
        logger.info(
            "Total request latency: %.2f sec",
            (ret_timer.elapsed_ms + llm_timer.elapsed_ms) / 1000.0
        )

        return llm_response, context_blocks
