METRIC_ALIASES = {
    "pat": "Net Profit",
    "profit after tax": "Net Profit",
    "net profit": "Net Profit",
    "profit for the year": "Net Profit",
    "revenue": "Revenue",
    "net sales": "Revenue",
    "operating revenue": "Revenue",
    "turnover": "Revenue",
    "sales": "Revenue",
    "total income": "Revenue",
    "ebitda": "EBITDA",
    "operating profit": "EBITDA",
    "ebit": "EBIT",
    "profit before tax": "EBIT",  # Strictly it's PBT but mapping loosely for simplicity.
    "eps": "EPS",
    "earnings per share": "EPS",
    "basic eps": "EPS",
    "diluted eps": "EPS",
    "roe": "ROE",
    "return on equity": "ROE",
    "roce": "ROCE",
    "return on capital employed": "ROCE",
    "assets": "Assets",
    "total assets": "Assets",
    "liabilities": "Liabilities",
    "total liabilities": "Liabilities",
    "cash": "Cash",
    "cash and cash equivalents": "Cash",
    "debt": "Debt",
    "total debt": "Debt",
    "borrowings": "Debt",
    "dividend": "Dividend",
    "dividend payout": "Dividend",
    "capex": "CapEx",
    "capital expenditure": "CapEx",
    "employee count": "Employee Count",
    "headcount": "Employee Count",
    "number of employees": "Employee Count",
}
