from typing import TypedDict, Annotated, Literal
from operator import add

class GraphState(TypedDict):
    """
    Maintains the state across LangGraph nodes globally accurately natively.
    """
    question: str
    company: str | None
    year: str | None
    
    # Conversations tracked sequentially mapping interactions safely
    messages: list[dict]
    
    # Extracted by Planner
    intent: str
    required_agents: list[str]
    
    # Aggregated retrieval mappings appended cumulatively
    retrieval_context: Annotated[list[dict], add]
    table_context: Annotated[list[dict], add]
    visual_context: Annotated[list[dict], add]
    metric_context: Annotated[list[dict], add]
    layout_context: Annotated[list[dict], add]
    
    # Finding structures generated by specialized networks natively
    draft_findings: Annotated[list[dict], add]
    
    # Tracking
    execution_trace: Annotated[list[dict], add]
    
    # Verification and formatting states gracefully tracked explicitly
    verified_findings: list[dict]
    unsupported_findings: list[dict]
    
    # Final Presentation Outputs natively
    confidence: float
    citations: list[dict]
    final_answer: str
